#!/bin/sh
#
# $kbyanc: libpperl/package/make-distfile,v 1.2 2005/06/03 20:28:59 kelly Exp $
# $NTTMCL$

PACKAGE=libpperl

WORKDIR=`mktemp -d -t distfile` || exit 1

DATESTR=`date '+%Y%m%d'`
NEWDISTFILE=${PACKAGE}-${DATESTR}.tar.gz
OLDDISTFILE=`ls -1 ${PACKAGE}*.tar.gz | tail -1`

#
# If we are running in a tree checked out from CVS, then use the same
# repository to check out the tree for packaging.  Note that we do not
# just package the tree we are running in as it may have local
# modifications, object files, or other cruft laying around.
#
if [ -r CVS/Entries ]; then
	CVSROOT=`cat CVS/Root`
fi

(
	cd $WORKDIR
	cvs -Q checkout -P ${PACKAGE}
	( cd ${PACKAGE}; sh autogen.sh )
	find -X . -name CVS | xargs rm -r
	rm -r ${PACKAGE}/package
	tar -czf $WORKDIR/$NEWDISTFILE ${PACKAGE}
)

if [ -z $OLDDISTFILE ]; then
	echo "new distfile $NEWDISTFILE"
	mv $WORKDIR/$NEWDISTFILE .
elif [ $OLDDISTFILE = $NEWDISTFILE ]; then
	echo "updating $NEWDISTFILE"
	mv $WORKDIR/$NEWDISTFILE .
elif [ `cmp -s $WORKDIR/$NEWDISTFILE $OLDDISTFILE; echo $?` -eq 0 ]; then
	echo "distfile $OLDDISTFILE is up to date"
else
	mv $WORKDIR/$NEWDISTFILE . && rm $OLDDISTFILE
	echo "replaced $OLDDISTFILE with $NEWDISTFILE"
fi

rm -rf $WORKDIR
